import = [
    # "~/.config/alacritty/themes/alacritty-theme/themes/rose-pine-moon.toml"
    # "~/.config/alacritty/themes/alacritty-theme/themes/snazzy.toml"
    # "~/.config/alacritty/themes/alacritty-theme/themes/moonlight_ii_vscode.toml"
    # "~/.config/alacritty/themes/alacritty-theme/themes/horizon-dark.toml"
    "~/.config/alacritty/moonlight_ii_vscode.toml"
]

[font]
size = 7

[window.padding]
x = 6
