[colors.primary]

background = "#161c23"
foreground = "#e5ded6"
# background = '#1e2030'
# foreground = '#7f85a3'

[colors.cursor]
text   = '#7f85a3'
# cursor = '#808080'
cursor = '#415367'

[colors.normal]
black   = '#444a73'
red     = '#ff5370'
green   = '#4fd6be'
yellow  = '#ffc777'
blue = "#36b2d4"
# blue    = '#3e68d7'
magenta = '#fc7b7b'
cyan    = '#86e1fc'
white   = '#d0d0d0'

[colors.bright]
black   = '#828bb8'
red     = '#ff98a4'
green   = '#c3e88d'
yellow  = '#ffc777'
blue    = '#82aaff'
magenta = '#ff966c'
cyan    = '#b4f9f8'
white   = '#5f8787'
